name: fb_chat_example
description: "A small chat app showing how to use firebase and firestore."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  chat_bubbles: ^1.6.0
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
